#http://flexget.com
flexget:
  destination: /var/lib/flexget/series.yml
  dropped_slug: dropped-shows
#http://trakt.tv/oauth/applications
trakt:
  access_token: Bearer access_token
  client_id: client_id
  client_secret: client_secret
  domain: api-v2launch.trakt.tv
  redirect_uri: urn:ietf:wg:oauth:2.0:oob
  refresh_token: refresh_token
  username: username
  pin: 0000
#http://transmissionbt.com
transmission:
  destination:
    movie: /media/Movies/
    show: /media/TV/
  downloads: /var/lib/transmission/downloads/
  tracker:
    movie:
    - movietracker.com
    show:
    - tvtracker.com
